# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7133e8e49aa8c266284f080afea484f6342571b70a479fb7e56d84c49488ac4ef1ac5add8ac15423399229913ebfba29a3885d3dd2984b2895fbc5e39b902973

test:
  secret_key_base: 2350ce275e7429880a1f85fc3b449593c043cf59ce0d822dc7e5ff9c21e86cdefbc73e425aa4b8cabcd8e2ffa97bf9e5a36daf96362b6616b698c8ec7a88a002

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
